services:
  warshati-frontend-deploy:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - PORT=${PORT}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "512M"
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
